services:
  aliyun-cdt-check:
    container_name: aliyun-cdt-check
    image: alanoo/aliyun-cdt-check:latest
    network_mode: bridge
    volumes:
      - /appdata/aliyun-cdt-check/config.json:/app/config.json
    restart: always
